[package]
name = "wasi-jsonrpsee"
description = "JSON-RPC client/server framework"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
publish = true

[lints]
workspace = true

[dependencies]
# No support for namespaced features yet so workspace dependencies are prefixed with `wasi-jsonrpsee-`.
# See https://github.com/rust-lang/cargo/issues/5565 for more details.
wasi-jsonrpsee-http-client = { workspace = true, optional = true }
wasi-jsonrpsee-ws-client = { workspace = true, optional = true }
wasi-jsonrpsee-wasm-client = { workspace = true, optional = true }
wasi-jsonrpsee-client-transport = { workspace = true, optional = true }
wasi-jsonrpsee-server = { workspace = true, optional = true }
wasi-jsonrpsee-proc-macros = { workspace = true, optional = true }
wasi-jsonrpsee-core = { workspace = true, optional = true }
wasi-jsonrpsee-types = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[features]
client-ws-transport-tls = ["wasi-jsonrpsee-client-transport/ws", "wasi-jsonrpsee-client-transport/tls-rustls-platform-verifier"]
client-ws-transport-no-tls = ["wasi-jsonrpsee-client-transport/ws"]
client-web-transport = ["wasi-jsonrpsee-client-transport/web"]
async-client = ["wasi-jsonrpsee-core/async-client"]
async-wasm-client = ["wasi-jsonrpsee-core/async-wasm-client"]
http-client = ["wasi-jsonrpsee-http-client", "wasi-jsonrpsee-types", "wasi-jsonrpsee-core/client"]
wasm-client = ["wasi-jsonrpsee-wasm-client", "wasi-jsonrpsee-types", "wasi-jsonrpsee-core/client"]
ws-client = ["wasi-jsonrpsee-ws-client", "wasi-jsonrpsee-types", "wasi-jsonrpsee-core/client"]
macros = ["wasi-jsonrpsee-proc-macros", "wasi-jsonrpsee-types", "tracing"]

client = ["http-client", "ws-client", "wasm-client", "client-ws-transport-tls", "client-web-transport", "async-client", "async-wasm-client", "client-core"]
client-core = ["wasi-jsonrpsee-core/client"]
server = ["wasi-jsonrpsee-server", "server-core", "wasi-jsonrpsee-types", "tokio"]
server-core = ["wasi-jsonrpsee-core/server"]
full = ["client", "server", "macros"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
all-features = true
